# Generated by Django 4.0.6 on 2023-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0002_delete_pollingunitresult_delete_wardresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollingUnitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('unique_ward_id', models.IntegerField(default=0)),
                ('polling_unit_number', models.IntegerField(default=0)),
                ('polling_unit_name', models.IntegerField(default='NULL')),
                ('polling_unit_description', models.TextField()),
                ('lat', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('long', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('entered_by_user', models.CharField(default='NULL', max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(default='NULL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='wardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50)),
                ('lga_id', models.IntegerField()),
                ('ward_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
