# Generated by Django 4.0.6 on 2023-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pollingUnitResult',
        ),
    ]
