# Generated by Django 4.0.6 on 2023-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_delete_pollingunitresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollingUnitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
