# Generated by Django 4.0.6 on 2023-06-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_delete_wardresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='wardResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50)),
                ('total_votes', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('ward_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
