# Generated by Django 4.0.6 on 2023-06-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_wardresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wardResult',
        ),
    ]
