# Generated by Django 4.0.6 on 2023-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_wardresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardresult',
            name='lga_id',
            field=models.IntegerField(null=True),
        ),
    ]
