# Generated by Django 4.0.6 on 2023-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_alter_wardresult_lga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunitresult',
            name='party_score',
            field=models.IntegerField(default=4570, null=True),
        ),
        migrations.AlterField(
            model_name='wardresult',
            name='lga_id',
            field=models.IntegerField(default=8700, null=True),
        ),
    ]
